### ISSUE TITLE
Plugin error in 10.13.6

### ISSUE THREAD

**Issue by LibertyType** [mekkablue/ShowAngledHandles#17] opened 2019-03-15 22:19 UTC
Just updated to 10.13.6 and am getting this in the Macro Panel:

Traceback (most recent call last):
  File "/Users/georgethomas2/Library/Application Support/Glyphs/Plugins/ShowAngledHandles.glyphsReporter/Contents/Resources/../MacOS/main.py", line 11, in <module>
    _run('plugin.py')
  File "/Users/georgethomas2/Library/Application Support/Glyphs/Plugins/ShowAngledHandles.glyphsReporter/Contents/Resources/../MacOS/main.py", line 9, in _run
    execfile(path, globals(), globals())
  File "/Users/georgethomas2/Library/Application Support/Glyphs/Plugins/ShowAngledHandles.glyphsReporter/Contents/Resources/plugin.py", line 57, in <module>
    class ShowAngledHandles(ReporterPlugin):
objc.error: ShowAngledHandles is overriding existing Objective-C class

**Uninstalled, then reinstalled, and got a new error:**

Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 1158, in drawForegroundForLayer_options_
  File "/Users/georgethomas2/Library/Application Support/Glyphs/Repositories/Show Angled Handles/ShowAngledHandles.glyphsReporter/Contents/Resources/plugin.py", line 99, in foreground
    self.markDuplicateSegments( layer, self.getScale() )
  File "/Users/georgethomas2/Library/Application Support/Glyphs/Repositories/Show Angled Handles/ShowAngledHandles.glyphsReporter/Contents/Resources/plugin.py", line 257, in markDuplicateSegments
    if s1 not in duplicates and s1 in (s2, s2[::-1]):
  File "GlyphsApp/objectsGS.py", line 817, in __getitem__
KeyError

**Comment by LibertyType** [comment] 2019-03-16 21:31
Today I'm not getting any feedback in the panel, so am going to close the issue since it could have happened before I updated to 1219; I don't remember the timing.

**Comment by LibertyType** [comment] 2019-04-06 01:08
G2.6.1 [1226] High Sierra -- New Errors in Macro Panel

Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 1158, in drawForegroundForLayer_options_
  File "plugin.py", line 97, in foreground
  File "plugin.py", line 271, in calcClosestInfo
AttributeError: 'NoneType' object has no attribute 'position'

Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 1158, in drawForegroundForLayer_options_
  File "/Users/georgethomas2/Library/Application Support/Glyphs/Repositories/Show Angled Handles/ShowAngledHandles.glyphsReporter/Contents/Resources/plugin.py", line 99, in foreground
    self.markDuplicateSegments( layer, self.getScale() )
  File "/Users/georgethomas2/Library/Application Support/Glyphs/Repositories/Show Angled Handles/ShowAngledHandles.glyphsReporter/Contents/Resources/plugin.py", line 257, in markDuplicateSegments
    if s1 not in duplicates and s1 in (s2, s2[::-1]):
  File "GlyphsApp/objectsGS.py", line 817, in __getitem__
KeyError

**Comment by mekkablue** [comment] 2019-04-08 17:45
There may be a bug in the python implementation of 1226. You may want to temporarily downgrade to 1225

**Comment by schriftgestalt** [comment] 2019-04-10 08:29
this is only a problem if another plugin is loading the robofab wrapper. Then `path.segments` implementation is overwritten and the API is different.

**Comment by mekkablue** [comment] 2019-04-18 09:50
I could not reproduce it (anymore). Will close the issue. Please reopen if it still occurs.

**Closed by mekkablue** 2019-04-18 09:50 UTC
